
Las variables de entorno son valores que se pueden utilizar en tus pipelines para almacenar información sensible o configuraciones específicas para cada entorno (como desarrollo, pruebas, producción). En el caso de las URL de la base de datos, es una práctica común definir diferentes URLs para cada ambiente, ya que las bases de datos de desarrollo, pruebas y producción pueden ser diferentes.

Para configurar variables de entorno en un pipeline de GitLab, sigue estos pasos:

Abre tu proyecto en GitLab y navega a la sección "Settings" (Configuración) en el menú de la izquierda.

En "CI/CD", busca la opción "Variables" o "Secret Variables" y haz clic en ella.

Aquí puedes definir variables de entorno para tu proyecto. Por ejemplo, puedes crear variables llamadas DEVELOPMENT_DB_URL, TEST_DB_URL y PRODUCTION_DB_URL. Configura los valores de estas variables con las URL de las bases de datos correspondientes a cada ambiente. Asegúrate de marcar la opción "Protected" si deseas que estas variables solo sean accesibles desde pipelines protegidos.

Una vez que hayas configurado las variables de entorno, puedes acceder a ellas en tu archivo .gitlab-ci.yml y utilizarlas en tus scripts de pipeline.

A continuación, te mostraré un ejemplo de cómo usar estas variables en un archivo .gitlab-ci.yml para un pipeline de despliegue simple en tres etapas: desarrollo, pruebas y producción. El pipeline incluirá pasos para migrar la base de datos y desplegar la aplicación.
stages:
  - desarrollo
  - pruebas
  - produccion

variables:
  DEVELOPMENT_DB_URL: "URL_DE_BASE_DE_DATOS_DE_DESARROLLO"
  TEST_DB_URL: "URL_DE_BASE_DE_DATOS_DE_PRUEBAS"
  PRODUCTION_DB_URL: "URL_DE_BASE_DE_DATOS_DE_PRODUCCION"

desarrollo:
  stage: desarrollo
  script:
    - echo "Desplegando en ambiente de desarrollo"
    - echo "Migrando la base de datos con $DEVELOPMENT_DB_URL"
    - # Comandos de despliegue y migración en desarrollo

pruebas:
  stage: pruebas
  script:
    - echo "Desplegando en ambiente de pruebas"
    - echo "Migrando la base de datos con $TEST_DB_URL"
    - # Comandos de despliegue y migración en pruebas

produccion:
  stage: produccion
  script:
    - echo "Desplegando en ambiente de producción"
    - echo "Migrando la base de datos con $PRODUCTION_DB_URL"
    - # Comandos de despliegue y migración en producción
En este ejemplo, las variables de entorno DEVELOPMENT_DB_URL, TEST_DB_URL y PRODUCTION_DB_URL se utilizan en los scripts de cada etapa del pipeline para migrar la base de datos y desplegar la aplicación en el ambiente correspondiente. Asegúrate de reemplazar las URLs ficticias en el ejemplo con las URLs reales de tus bases de datos.

Al definir variables de entorno de esta manera, puedes mantener tus configuraciones seguras y específicas para cada ambiente, lo que es esencial en un proceso de despliegue continuo.